09/26/2013 09:33:48.387 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 703, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 68, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 09:35:51.700 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 706, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 68, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 09:38:14.22 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 706, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 71, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 632, in run_command
    sys.exit()
SystemExit

09/26/2013 09:38:54.535 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 706, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 56, in main
    player_inventory = game_map.player[0].item[0].attrs['name']
IndexError: list index out of range

09/26/2013 09:40:49.525 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 710, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 68, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 09:43:05.296 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 710, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 71, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 566, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 298, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 346, in experience_system
    game_map.player.attrs['strength'] = characters['player_stats']['Strength']
AttributeError: 'list' object has no attribute 'attrs'

09/26/2013 09:44:12.650 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 710, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 68, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 09:44:53.148 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 710, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 56, in main
    player_inventory = game_map.player[0].item[0].attrs['name']
IndexError: list index out of range

09/26/2013 09:45:36.257 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 710, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 68, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 09:46:12.317 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 710, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 68, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 09:47:46.12 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 713, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 71, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 569, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 298, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 347, in experience_system
    print characters.attrs['strength']
AttributeError: 'dict' object has no attribute 'attrs'

09/26/2013 09:48:39.708 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 714, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 71, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 570, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 298, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 347, in experience_system
    print characters['strength']
KeyError: 'strength'

09/26/2013 09:49:10.763 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 713, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 71, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 569, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 298, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 347, in experience_system
    print player.children['strength']
TypeError: list indices must be integers, not str

09/26/2013 09:49:46.227 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 716, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 71, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 572, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 298, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 349, in experience_system
    print player.children[2]
IndexError: list index out of range

09/26/2013 09:51:05.994 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 716, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 71, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 572, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 298, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 352, in experience_system
    print characters.attrs['strength']
AttributeError: 'dict' object has no attribute 'attrs'

09/26/2013 09:53:38.432 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 721, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 71, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 577, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 298, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 347, in experience_system
    player.attrs['strength'] = player.attrs['strength'] + 1
TypeError: coercing to Unicode: need string or buffer, int found

09/26/2013 09:55:35.644 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 714, in <module>
    locked = dict()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 68, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 09:55:35.766 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 721, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 68, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 09:55:35.886 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 721, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 68, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 09:56:16.704 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 721, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 71, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 577, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 230, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/26/2013 10:01:12.817 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 723, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 71, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 579, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 298, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 349, in experience_system
    player.attrs['strength'] = player.attrs['strength'] + nstr
TypeError: coercing to Unicode: need string or buffer, int found

09/26/2013 10:04:05.15 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 723, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 68, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:04:05.944 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 723, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 68, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:21:19.797 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 724, in <module>
    game_map.player.attrs['level'] = 'Teddy'
AttributeError: 'NoneType' object has no attribute 'player'

09/26/2013 10:21:58.93 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 728, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 54, in main
    game_map.player.attrs['level'] = 'Teddy'
AttributeError: 'list' object has no attribute 'attrs'

09/26/2013 10:22:16.914 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 728, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 56, in main
    with open('test.xml') as fout:
IOError: [Errno 2] No such file or directory: 'test.xml'

09/26/2013 10:22:52.197 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 728, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 76, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 654, in run_command
    sys.exit()
SystemExit

09/26/2013 10:26:05.870 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 728, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 76, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 584, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 303, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 326, in experience_system
    characters["Player Level"] = int(characters["Player Level"]) + 1
ValueError: invalid literal for int() with base 10: 'Teddy'

09/26/2013 10:26:48.672 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 724, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 580, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 299, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 350, in experience_system
    player[0].attrs['strength'] = characters['player_stats']['Strength']
TypeError: 'player_q2class' object does not support indexing

09/26/2013 10:27:47.164 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 724, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 580, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 231, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/26/2013 10:28:18.736 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 724, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 57, in main
    player_inventory = game_map.player[0].item[0].attrs['name']
IndexError: list index out of range

09/26/2013 10:29:19.254 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 724, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:30:24.737 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 725, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 581, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 299, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 350, in experience_system
    game_map.player.attrs['strength'] = characters['player_stats']['Strength']
AttributeError: 'list' object has no attribute 'attrs'

09/26/2013 10:30:44.487 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 725, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 581, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 299, in battle_system
    experience_system(int(experience))
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 353, in experience_system
    print game_map.player.attrs['strength']
AttributeError: 'list' object has no attribute 'attrs'

09/26/2013 10:31:21.529 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 725, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:31:21.681 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 725, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:34:42.339 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 725, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:38:04.493 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 723, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:38:04.637 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 723, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:42:28.874 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 700, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 556, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 231, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/26/2013 10:46:30.222 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 700, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:46:30.367 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 700, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:48:16.257 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 700, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 626, in run_command
    sys.exit()
SystemExit

09/26/2013 10:48:44.677 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 700, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 626, in run_command
    sys.exit()
SystemExit

09/26/2013 10:50:44.488 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 703, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:52:30.589 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 702, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:58:14.944 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 726, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 10:59:02.383 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 726, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 11:04:23.253 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 726, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 11:07:16.322 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 726, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 11:11:09.112 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 729, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 11:13:37.312 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 729, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 11:23:06.322 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 730, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 11:59:32.655 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 730, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 12:06:51.699 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 730, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 599, in run_command
    if req == "None" or req in inv:
TypeError: argument of type 'item_q2class' is not iterable

09/26/2013 12:10:59.895 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 730, in <module>
    try:
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 12:11:00.32 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 731, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 12:11:00.757 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 731, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 12:11:17.218 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 731, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 12:13:17.960 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 731, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 12:28:45.559 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 730, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 12:30:44.638 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 730, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 586, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 304, in battle_system
    end_the_game(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 569, in end_the_game
    sys.exit()
SystemExit

09/26/2013 12:38:02.646 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 730, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 69, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 13:27:52.993 Traceback (most recent call last):
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\inventory play.py", line 730, in <module>
    main()
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\inventory play.py", line 72, in main
    current_room = run_command(current_room, verb, noun)
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\inventory play.py", line 661, in run_command
    inn_system(room)
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\inventory play.py", line 397, in inn_system
    character['player_stats']['health'] = character["player_stats"]['health'] = base_health + (character['player_stats']['Endurance'] * 2)
TypeError: unsupported operand type(s) for +: 'int' and 'unicode'

09/26/2013 13:47:53.537 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 730, in <module>
    locked[room_exit.attrs["name"]] = room_exit.attrs["locked"]
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 72, in main
    os.system('CLS')
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 586, in run_command
    #hopefully one day will check to see if doors are locked, and if so, let me pass through them if I have the key.
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 304, in battle_system
    wallet_system(gold)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 569, in end_the_game
    print 'Hope the music and battle system wasnt too annoying.'
SystemExit

09/26/2013 13:54:47.250 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 735, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 73, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 661, in run_command
    sys.exit()
SystemExit

09/26/2013 13:55:34.249 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 735, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/inventory play.py", line 70, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 13:57:49.363 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 733, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 64, in main
    intro()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 186, in intro
    game_map.itro.remove(item)
AttributeError: 'map_q2class' object has no attribute 'itro'

09/26/2013 13:58:47.267 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 733, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 73, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 659, in run_command
    sys.exit()
SystemExit

09/26/2013 13:58:50.880 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 733, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 64, in main
    intro()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 179, in intro
    item = game_map.intro[0]
IndexError: list index out of range

09/26/2013 13:59:15.44 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 735, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 70, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 14:23:36.840 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 738, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 69, in main
    describe(current_room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 457, in describe
    set_color(fg = 1, bk = None)
NameError: global name 'set_color' is not defined

09/26/2013 14:26:25.396 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 736, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 14:29:40.745 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 738, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 14:31:52.853 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 737, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 699, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 490, in candy_system
    if noun in inv:
TypeError: argument of type 'item_q2class' is not iterable

09/26/2013 14:33:33.607 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 737, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 699, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 490, in candy_system
    if noun in inv:
TypeError: argument of type 'item_q2class' is not iterable

09/26/2013 14:35:35.709 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 737, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 699, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 493, in candy_system
    character['player_stats']['health'] = character["player_stats"]['health'] = base_health + (character['player_stats']['Endurance'] * 2)
TypeError: unsupported operand type(s) for +: 'int' and 'unicode'

09/26/2013 14:36:20.985 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 737, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 699, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 495, in candy_system
    player.item.remove('candy')
ValueError: list.remove(x): x not in list

09/26/2013 14:38:29.897 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 744, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 706, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 502, in candy_system
    player.item.remove(noun)
ValueError: list.remove(x): x not in list

09/26/2013 14:39:08.422 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 744, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 706, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 502, in candy_system
    game_map.player.item.remove(noun)
AttributeError: 'list' object has no attribute 'item'

09/26/2013 14:39:36.152 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 744, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 706, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 502, in candy_system
    game_map.player[0].item.remove(noun)
ValueError: list.remove(x): x not in list

09/26/2013 14:40:20.292 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 745, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 707, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 503, in candy_system
    game_map.player[0].item.remove(name)
ValueError: list.remove(x): x not in list

09/26/2013 14:42:29.604 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 745, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 707, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 503, in candy_system
    game_map.player[0].item.remove(noun)
ValueError: list.remove(x): x not in list

09/26/2013 14:43:03.381 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 745, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 707, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 503, in candy_system
    game_map.player[0].item.remove('candy')
ValueError: list.remove(x): x not in list

09/26/2013 14:43:36.434 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 745, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 707, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 503, in candy_system
    player[0].item.remove('candy')
TypeError: 'player_q2class' object does not support indexing

09/26/2013 14:43:57.977 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 745, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 707, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 503, in candy_system
    player[0].item[0].remove('candy')
TypeError: 'player_q2class' object does not support indexing

09/26/2013 14:44:20.747 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 745, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 707, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 503, in candy_system
    player.item.remove('candy')
ValueError: list.remove(x): x not in list

09/26/2013 14:44:47.381 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 746, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 708, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 504, in candy_system
    player.item.remove('candy')
ValueError: list.remove(x): x not in list

09/26/2013 14:45:20.59 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 746, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 708, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 499, in candy_system
    print player.item.attrs['name']
AttributeError: 'list' object has no attribute 'attrs'

09/26/2013 14:45:47.644 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 746, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 708, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 499, in candy_system
    print player[0].item.attrs['name']
TypeError: 'player_q2class' object does not support indexing

09/26/2013 14:46:46.759 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 745, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 707, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 503, in candy_system
    game_map.player[0].item.remove(name)
ValueError: list.remove(x): x not in list

09/26/2013 14:47:14.58 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 746, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 708, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 504, in candy_system
    game_map.player[0].item.remove(name)
ValueError: list.remove(x): x not in list

09/26/2013 14:47:50.435 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 747, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 709, in run_command
    candy_system(room, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 505, in candy_system
    game_map.player[0].item.remove(name)
ValueError: list.remove(x): x not in list

09/26/2013 14:54:10.339 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 729, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 14:58:31.729 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 729, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 15:04:04.92 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 729, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 15:04:04.217 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 729, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 33, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/26/2013 15:06:09.491 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 729, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 585, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 234, in battle_system
    command = raw_input('What would you like to do>>>')
EOFError: EOF when reading a line

09/26/2013 15:10:30.212 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 729, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 655, in run_command
    sys.exit()
SystemExit

09/26/2013 15:17:45.498 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 730, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 15:20:22.721 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 731, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 15:22:04.11 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 732, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 33, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/26/2013 15:25:12.76 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 732, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 15:26:51.317 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 732, in <module>
    exception_string = traceback.format_exc()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 15:27:53.240 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 730, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 656, in run_command
    sys.exit()
SystemExit

09/26/2013 15:42:11.248 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 731, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 16:09:05.560 Traceback (most recent call last):
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\Text_of_Mana.py", line 731, in <module>
    main()
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\Text_of_Mana.py", line 585, in run_command
    battle_system(room, monsters)
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\Text_of_Mana.py", line 308, in battle_system
    end_the_game(room)
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\Text_of_Mana.py", line 568, in end_the_game
    sys.exit()
SystemExit

09/26/2013 16:13:02.607 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 731, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 16:13:35.159 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 731, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 16:25:20.739 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 742, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 69, in main
    describe(current_room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 455, in describe
    print room.text[0].value
AttributeError: 'NoneType' object has no attribute 'text'

09/26/2013 16:33:55.178 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 787, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 656, in run_command
    sys.exit()
SystemExit

09/26/2013 16:38:18.213 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 791, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 16:39:22.358 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 799, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 16:50:11.806 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 804, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 296, in battle_system
    raw_input('...')
EOFError: EOF when reading a line

09/26/2013 17:07:58.875 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 804, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 295, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 800, in high_score
    fout.write(score, name)
TypeError: function takes exactly 1 argument (2 given)

09/26/2013 17:09:08.183 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 805, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 297, in battle_system
    sys.exit()
SystemExit

09/26/2013 17:14:35.774 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 805, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 296, in battle_system
    raw_input('...')
EOFError: EOF when reading a line

09/26/2013 17:16:03.481 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 808, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 296, in battle_system
    raw_input('...')
EOFError: EOF when reading a line

09/26/2013 17:16:52.519 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 809, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 295, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 802, in high_score
    for item in fout:
IOError: File not open for reading

09/26/2013 17:17:46.468 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 813, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 295, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 806, in high_score
    for item in fout:
IOError: File not open for reading

09/26/2013 17:18:44.201 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 813, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 33, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/26/2013 17:19:36.679 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 813, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 295, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 801, in high_score
    for item in read_data:
TypeError: 'builtin_function_or_method' object is not iterable

09/26/2013 17:21:44.555 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 813, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 295, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 806, in high_score
    for item in fout:
IOError: File not open for reading

09/26/2013 17:24:02.373 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 812, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 295, in battle_system
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 805, in high_score
    for item in fout:
IOError: File not open for reading

09/26/2013 19:33:39.149 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 808, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 33, in main
    choice = raw_input("choose a game or type 'N' for a new game\n>")
EOFError: EOF when reading a line

09/26/2013 19:36:53.856 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 808, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 309, in battle_system
    end_the_game(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 549, in end_the_game
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 797, in high_score
    name = raw_input('>>>')
EOFError: EOF when reading a line

09/26/2013 19:38:34.766 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 808, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 587, in run_command
    battle_system(room, monsters)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 309, in battle_system
    end_the_game(room)
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 549, in end_the_game
    high_score()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 797, in high_score
    name = raw_input('>>>')
EOFError: EOF when reading a line

09/26/2013 19:57:22.762 Traceback (most recent call last):
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 808, in <module>
    main()
  File "C:/Users/thubbard/Desktop/Project_R_Projects/Text_Adventure/API/Text_of_Mana.py", line 71, in main
    command = raw_input(">")
EOFError: EOF when reading a line

09/26/2013 20:23:41.660 Traceback (most recent call last):
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\Text_of_Mana.py", line 808, in <module>
    main()
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\Text_of_Mana.py", line 74, in main
    current_room = run_command(current_room, verb, noun)
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\Text_of_Mana.py", line 663, in run_command
    inn_system(room)
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\Text_of_Mana.py", line 403, in inn_system
    save_game(room)
  File "C:\Users\thubbard\Desktop\Project_R_Projects\Text_Adventure\API\Text_of_Mana.py", line 428, in save_game
    with open("saved_games\\" + save_file + ".xml", "w") as f:
IOError: [Errno 22] invalid mode ('w') or filename: 'saved_games\\wtf julie?!?!.xml'

